// Code generated by go-swagger; DO NOT EDIT.

package aggregates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetV1AggregatesHandlerFunc turns a function with the right signature into a get v1 aggregates handler
type GetV1AggregatesHandlerFunc func(GetV1AggregatesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1AggregatesHandlerFunc) Handle(params GetV1AggregatesParams) middleware.Responder {
	return fn(params)
}

// GetV1AggregatesHandler interface for that can handle valid get v1 aggregates params
type GetV1AggregatesHandler interface {
	Handle(GetV1AggregatesParams) middleware.Responder
}

// NewGetV1Aggregates creates a new http.Handler for the get v1 aggregates operation
func NewGetV1Aggregates(ctx *middleware.Context, handler GetV1AggregatesHandler) *GetV1Aggregates {
	return &GetV1Aggregates{Context: ctx, Handler: handler}
}

/*
	GetV1Aggregates swagger:route GET /v1/aggregates aggregates getV1Aggregates

get aggregates for weekly added records
*/
type GetV1Aggregates struct {
	Context *middleware.Context
	Handler GetV1AggregatesHandler
}

func (o *GetV1Aggregates) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetV1AggregatesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
