// Code generated by go-swagger; DO NOT EDIT.

package aggregates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"metrics/swagger_gen/models"
)

// GetV1AggregatesOKCode is the HTTP code returned for type GetV1AggregatesOK
const GetV1AggregatesOKCode int = 200

/*
GetV1AggregatesOK OK

swagger:response getV1AggregatesOK
*/
type GetV1AggregatesOK struct {

	/*
	  In: Body
	*/
	Payload models.AggregatesResponse `json:"body,omitempty"`
}

// NewGetV1AggregatesOK creates GetV1AggregatesOK with default headers values
func NewGetV1AggregatesOK() *GetV1AggregatesOK {

	return &GetV1AggregatesOK{}
}

// WithPayload adds the payload to the get v1 aggregates o k response
func (o *GetV1AggregatesOK) WithPayload(payload models.AggregatesResponse) *GetV1AggregatesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 aggregates o k response
func (o *GetV1AggregatesOK) SetPayload(payload models.AggregatesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AggregatesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
