// Code generated by go-swagger; DO NOT EDIT.

package aggregates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"metrics/swagger_gen/models"
)

// GetV1AggregatesWeeklyOKCode is the HTTP code returned for type GetV1AggregatesWeeklyOK
const GetV1AggregatesWeeklyOKCode int = 200

/*
GetV1AggregatesWeeklyOK OK

swagger:response getV1AggregatesWeeklyOK
*/
type GetV1AggregatesWeeklyOK struct {

	/*
	  In: Body
	*/
	Payload models.AggregatesResponse `json:"body,omitempty"`
}

// NewGetV1AggregatesWeeklyOK creates GetV1AggregatesWeeklyOK with default headers values
func NewGetV1AggregatesWeeklyOK() *GetV1AggregatesWeeklyOK {

	return &GetV1AggregatesWeeklyOK{}
}

// WithPayload adds the payload to the get v1 aggregates weekly o k response
func (o *GetV1AggregatesWeeklyOK) WithPayload(payload models.AggregatesResponse) *GetV1AggregatesWeeklyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 aggregates weekly o k response
func (o *GetV1AggregatesWeeklyOK) SetPayload(payload models.AggregatesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1AggregatesWeeklyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
