FROM node:20.11.0 AS install
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn

FROM node:20.11.0 as test
WORKDIR /app
COPY prisma ./prisma/
COPY --from=install /app/node_modules ./node_modules
RUN npx prisma generate
COPY . .
EXPOSE 3332
CMD [ "yarn", "test:migrate" ]