FROM node:20.11.0-alpine3.18 AS install
RUN apk add openssl curl
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn

FROM node:20.11.0-alpine3.18 as test
RUN apk add openssl curl
WORKDIR /app
COPY prisma ./prisma/
COPY --from=install /app/node_modules ./node_modules
RUN npx prisma generate
COPY . .
EXPOSE 3332
CMD [ "yarn", "test:migrate" ]