version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
  credential-schema:
    image: cred
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3333:3333'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      IDENTITY_BASE_URL: "http://identity-service:3332"
      ENABLE_AUTH: "false" 
      ANCHOR_TO_CORD: "${ANCHOR_TO_CORD}"
      ISSUER_AGENT_BASE_URL: "${ISSUER_AGENT_BASE_URL}"
    networks:
      rcw-test:
      default:


networks:
  rcw-test:
    external: true

volumes:
  data: