// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Notification service
//
//  Notification service
//  Schemes:
//    https
//  Host: sunbirdrc.dev
//  BasePath: /notification-service/v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
