export registry_url="http://localhost:8081"
export keycloak_realmName="PartnerRegistry"
export keycloak_url="http://localhost:8080/auth/admin/realms/"
export notification_url="http://localhost:9000/v1/notification/send/sync"
export systemAdminId="emailId"
export systemAdminPassword="password"