// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UploadedFileDTO uploaded file d t o
//
// swagger:model UploadedFileDTO
type UploadedFileDTO struct {

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// date
	Date string `json:"date,omitempty"`

	// filename
	Filename string `json:"filename,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// total record
	TotalRecord int64 `json:"totalRecord,omitempty"`

	// updated at
	UpdatedAt string `json:"updatedAt,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this uploaded file d t o
func (m *UploadedFileDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this uploaded file d t o based on context it is used
func (m *UploadedFileDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UploadedFileDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UploadedFileDTO) UnmarshalBinary(b []byte) error {
	var res UploadedFileDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
