// Code generated by go-swagger; DO NOT EDIT.

package uploaded_files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetV1UploadedFilesParams creates a new GetV1UploadedFilesParams object
// no default values defined in spec.
func NewGetV1UploadedFilesParams() GetV1UploadedFilesParams {

	return GetV1UploadedFilesParams{}
}

// GetV1UploadedFilesParams contains all the bound params for the get v1 uploaded files operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetV1UploadedFiles
type GetV1UploadedFilesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetV1UploadedFilesParams() beforehand.
func (o *GetV1UploadedFilesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
