// Code generated by go-swagger; DO NOT EDIT.

package download_file_report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetV1DownloadFileNameParams creates a new GetV1DownloadFileNameParams object
// no default values defined in spec.
func NewGetV1DownloadFileNameParams() GetV1DownloadFileNameParams {

	return GetV1DownloadFileNameParams{}
}

// GetV1DownloadFileNameParams contains all the bound params for the get v1 download file name operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetV1DownloadFileName
type GetV1DownloadFileNameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*File name
	  Required: true
	  In: path
	*/
	FileName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetV1DownloadFileNameParams() beforehand.
func (o *GetV1DownloadFileNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rFileName, rhkFileName, _ := route.Params.GetOK("fileName")
	if err := o.bindFileName(rFileName, rhkFileName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFileName binds and validates parameter FileName from path.
func (o *GetV1DownloadFileNameParams) bindFileName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.FileName = raw

	return nil
}
