// Code generated by go-swagger; DO NOT EDIT.

package download_file_report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetV1DownloadFileNameHandlerFunc turns a function with the right signature into a get v1 download file name handler
type GetV1DownloadFileNameHandlerFunc func(GetV1DownloadFileNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1DownloadFileNameHandlerFunc) Handle(params GetV1DownloadFileNameParams) middleware.Responder {
	return fn(params)
}

// GetV1DownloadFileNameHandler interface for that can handle valid get v1 download file name params
type GetV1DownloadFileNameHandler interface {
	Handle(GetV1DownloadFileNameParams) middleware.Responder
}

// NewGetV1DownloadFileName creates a new http.Handler for the get v1 download file name operation
func NewGetV1DownloadFileName(ctx *middleware.Context, handler GetV1DownloadFileNameHandler) *GetV1DownloadFileName {
	return &GetV1DownloadFileName{Context: ctx, Handler: handler}
}

/*GetV1DownloadFileName swagger:route GET /v1/download/{fileName} downloadFileReport getV1DownloadFileName

download the success and error report of file uploaded

*/
type GetV1DownloadFileName struct {
	Context *middleware.Context
	Handler GetV1DownloadFileNameHandler
}

func (o *GetV1DownloadFileName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1DownloadFileNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
