// Code generated by go-swagger; DO NOT EDIT.

package upload_and_create_records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"bulk_issuance/swagger_gen/models"
)

// PostV1EntityNameUploadHandlerFunc turns a function with the right signature into a post v1 entity name upload handler
type PostV1EntityNameUploadHandlerFunc func(PostV1EntityNameUploadParams, *models.JWTClaimBody) middleware.Responder

// Handle executing the request and returning a response
func (fn PostV1EntityNameUploadHandlerFunc) Handle(params PostV1EntityNameUploadParams, principal *models.JWTClaimBody) middleware.Responder {
	return fn(params, principal)
}

// PostV1EntityNameUploadHandler interface for that can handle valid post v1 entity name upload params
type PostV1EntityNameUploadHandler interface {
	Handle(PostV1EntityNameUploadParams, *models.JWTClaimBody) middleware.Responder
}

// NewPostV1EntityNameUpload creates a new http.Handler for the post v1 entity name upload operation
func NewPostV1EntityNameUpload(ctx *middleware.Context, handler PostV1EntityNameUploadHandler) *PostV1EntityNameUpload {
	return &PostV1EntityNameUpload{Context: ctx, Handler: handler}
}

/*PostV1EntityNameUpload swagger:route POST /v1/{entityName}/upload uploadAndCreateRecords postV1EntityNameUpload

upload the file and create records

*/
type PostV1EntityNameUpload struct {
	Context *middleware.Context
	Handler PostV1EntityNameUploadHandler
}

func (o *PostV1EntityNameUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostV1EntityNameUploadParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.JWTClaimBody
	if uprinc != nil {
		principal = uprinc.(*models.JWTClaimBody) // this is really a models.JWTClaimBody, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
