// Code generated by go-swagger; DO NOT EDIT.

package upload_and_create_records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bulk_issuance/swagger_gen/models"
)

// PostV1UploadFilesVCNameOKCode is the HTTP code returned for type PostV1UploadFilesVCNameOK
const PostV1UploadFilesVCNameOKCode int = 200

/*PostV1UploadFilesVCNameOK OK

swagger:response postV1UploadFilesVCNameOK
*/
type PostV1UploadFilesVCNameOK struct {

	/*
	  In: Body
	*/
	Payload models.CreateRecordResponse `json:"body,omitempty"`
}

// NewPostV1UploadFilesVCNameOK creates PostV1UploadFilesVCNameOK with default headers values
func NewPostV1UploadFilesVCNameOK() *PostV1UploadFilesVCNameOK {

	return &PostV1UploadFilesVCNameOK{}
}

// WithPayload adds the payload to the post v1 upload files v c name o k response
func (o *PostV1UploadFilesVCNameOK) WithPayload(payload models.CreateRecordResponse) *PostV1UploadFilesVCNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 upload files v c name o k response
func (o *PostV1UploadFilesVCNameOK) SetPayload(payload models.CreateRecordResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1UploadFilesVCNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostV1UploadFilesVCNameNotFoundCode is the HTTP code returned for type PostV1UploadFilesVCNameNotFound
const PostV1UploadFilesVCNameNotFoundCode int = 404

/*PostV1UploadFilesVCNameNotFound Not found

swagger:response postV1UploadFilesVCNameNotFound
*/
type PostV1UploadFilesVCNameNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostV1UploadFilesVCNameNotFound creates PostV1UploadFilesVCNameNotFound with default headers values
func NewPostV1UploadFilesVCNameNotFound() *PostV1UploadFilesVCNameNotFound {

	return &PostV1UploadFilesVCNameNotFound{}
}

// WithPayload adds the payload to the post v1 upload files v c name not found response
func (o *PostV1UploadFilesVCNameNotFound) WithPayload(payload string) *PostV1UploadFilesVCNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 upload files v c name not found response
func (o *PostV1UploadFilesVCNameNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1UploadFilesVCNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostV1UploadFilesVCNameInternalServerErrorCode is the HTTP code returned for type PostV1UploadFilesVCNameInternalServerError
const PostV1UploadFilesVCNameInternalServerErrorCode int = 500

/*PostV1UploadFilesVCNameInternalServerError Internal Server Error

swagger:response postV1UploadFilesVCNameInternalServerError
*/
type PostV1UploadFilesVCNameInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostV1UploadFilesVCNameInternalServerError creates PostV1UploadFilesVCNameInternalServerError with default headers values
func NewPostV1UploadFilesVCNameInternalServerError() *PostV1UploadFilesVCNameInternalServerError {

	return &PostV1UploadFilesVCNameInternalServerError{}
}

// WithPayload adds the payload to the post v1 upload files v c name internal server error response
func (o *PostV1UploadFilesVCNameInternalServerError) WithPayload(payload string) *PostV1UploadFilesVCNameInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 upload files v c name internal server error response
func (o *PostV1UploadFilesVCNameInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1UploadFilesVCNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
