// Code generated by go-swagger; DO NOT EDIT.

package upload_and_create_records

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"bulk_issuance/swagger_gen/models"
)

// PostV1SchemaNameUploadHandlerFunc turns a function with the right signature into a post v1 schema name upload handler
type PostV1SchemaNameUploadHandlerFunc func(PostV1SchemaNameUploadParams, *models.JWTClaimBody) middleware.Responder

// Handle executing the request and returning a response
func (fn PostV1SchemaNameUploadHandlerFunc) Handle(params PostV1SchemaNameUploadParams, principal *models.JWTClaimBody) middleware.Responder {
	return fn(params, principal)
}

// PostV1SchemaNameUploadHandler interface for that can handle valid post v1 schema name upload params
type PostV1SchemaNameUploadHandler interface {
	Handle(PostV1SchemaNameUploadParams, *models.JWTClaimBody) middleware.Responder
}

// NewPostV1SchemaNameUpload creates a new http.Handler for the post v1 schema name upload operation
func NewPostV1SchemaNameUpload(ctx *middleware.Context, handler PostV1SchemaNameUploadHandler) *PostV1SchemaNameUpload {
	return &PostV1SchemaNameUpload{Context: ctx, Handler: handler}
}

/*
	PostV1SchemaNameUpload swagger:route POST /v1/{schemaName}/upload uploadAndCreateRecords postV1SchemaNameUpload

upload the file and create records
*/
type PostV1SchemaNameUpload struct {
	Context *middleware.Context
	Handler PostV1SchemaNameUploadHandler
}

func (o *PostV1SchemaNameUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostV1SchemaNameUploadParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.JWTClaimBody
	if uprinc != nil {
		principal = uprinc.(*models.JWTClaimBody) // this is really a models.JWTClaimBody, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostV1SchemaNameUploadBadRequestBody post v1 schema name upload bad request body
//
// swagger:model PostV1SchemaNameUploadBadRequestBody
type PostV1SchemaNameUploadBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this post v1 schema name upload bad request body
func (o *PostV1SchemaNameUploadBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post v1 schema name upload bad request body based on context it is used
func (o *PostV1SchemaNameUploadBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostV1SchemaNameUploadBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostV1SchemaNameUploadBadRequestBody) UnmarshalBinary(b []byte) error {
	var res PostV1SchemaNameUploadBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
