// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Message.proto
// Protobuf Java Version: 4.27.3

package org.sunbird.akka.core;

public final class MessageProtos {
  private MessageProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
            com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
            /* major= */ 4,
            /* minor= */ 27,
            /* patch= */ 3,
            /* suffix= */ "",
            MessageProtos.class.getName());
  }
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageOption}
   */
  public enum MessageOption
          implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SEND_AND_FORGET = 0;</code>
     */
    SEND_AND_FORGET(0),
    /**
     * <code>GET_BACK_RESPONSE = 1;</code>
     */
    GET_BACK_RESPONSE(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
              com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
              /* major= */ 4,
              /* minor= */ 27,
              /* patch= */ 3,
              /* suffix= */ "",
              MessageOption.class.getName());
    }
    /**
     * <code>SEND_AND_FORGET = 0;</code>
     */
    public static final int SEND_AND_FORGET_VALUE = 0;
    /**
     * <code>GET_BACK_RESPONSE = 1;</code>
     */
    public static final int GET_BACK_RESPONSE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageOption valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageOption forNumber(int value) {
      switch (value) {
        case 0: return SEND_AND_FORGET;
        case 1: return GET_BACK_RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageOption>
    internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
            MessageOption> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageOption>() {
              public MessageOption findValueByNumber(int number) {
                return MessageOption.forNumber(number);
              }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return org.sunbird.akka.core.MessageProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageOption[] VALUES = values();

    public static MessageOption valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
                "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageOption(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageOption)
  }

  public interface MessageOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Message)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string targetActorName = 1;</code>
     * @return The targetActorName.
     */
    java.lang.String getTargetActorName();
    /**
     * <code>string targetActorName = 1;</code>
     * @return The bytes for targetActorName.
     */
    com.google.protobuf.ByteString
    getTargetActorNameBytes();

    /**
     * <code>string sourceActorName = 2;</code>
     * @return The sourceActorName.
     */
    java.lang.String getSourceActorName();
    /**
     * <code>string sourceActorName = 2;</code>
     * @return The bytes for sourceActorName.
     */
    com.google.protobuf.ByteString
    getSourceActorNameBytes();

    /**
     * <code>string performOperation = 3;</code>
     * @return The performOperation.
     */
    java.lang.String getPerformOperation();
    /**
     * <code>string performOperation = 3;</code>
     * @return The bytes for performOperation.
     */
    com.google.protobuf.ByteString
    getPerformOperationBytes();

    /**
     * <code>string id = 4;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 4;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
    getIdBytes();

    /**
     * <code>.MessageOption msgOption = 5;</code>
     * @return The enum numeric value on the wire for msgOption.
     */
    int getMsgOptionValue();
    /**
     * <code>.MessageOption msgOption = 5;</code>
     * @return The msgOption.
     */
    org.sunbird.akka.core.MessageProtos.MessageOption getMsgOption();

    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     * @return Whether the payload field is set.
     */
    boolean hasPayload();
    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     * @return The payload.
     */
    com.google.protobuf.Value getPayload();
    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     */
    com.google.protobuf.ValueOrBuilder getPayloadOrBuilder();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
          com.google.protobuf.GeneratedMessage implements
          // @@protoc_insertion_point(message_implements:Message)
          MessageOrBuilder {
    private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
              com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
              /* major= */ 4,
              /* minor= */ 27,
              /* patch= */ 3,
              /* suffix= */ "",
              Message.class.getName());
    }
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      targetActorName_ = "";
      sourceActorName_ = "";
      performOperation_ = "";
      id_ = "";
      msgOption_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return org.sunbird.akka.core.MessageProtos.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return org.sunbird.akka.core.MessageProtos.internal_static_Message_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      org.sunbird.akka.core.MessageProtos.Message.class, org.sunbird.akka.core.MessageProtos.Message.Builder.class);
    }

    private int bitField0_;
    public static final int TARGETACTORNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object targetActorName_ = "";
    /**
     * <code>string targetActorName = 1;</code>
     * @return The targetActorName.
     */
    @java.lang.Override
    public java.lang.String getTargetActorName() {
      java.lang.Object ref = targetActorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetActorName_ = s;
        return s;
      }
    }
    /**
     * <code>string targetActorName = 1;</code>
     * @return The bytes for targetActorName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getTargetActorNameBytes() {
      java.lang.Object ref = targetActorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        targetActorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCEACTORNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sourceActorName_ = "";
    /**
     * <code>string sourceActorName = 2;</code>
     * @return The sourceActorName.
     */
    @java.lang.Override
    public java.lang.String getSourceActorName() {
      java.lang.Object ref = sourceActorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceActorName_ = s;
        return s;
      }
    }
    /**
     * <code>string sourceActorName = 2;</code>
     * @return The bytes for sourceActorName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getSourceActorNameBytes() {
      java.lang.Object ref = sourceActorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        sourceActorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERFORMOPERATION_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object performOperation_ = "";
    /**
     * <code>string performOperation = 3;</code>
     * @return The performOperation.
     */
    @java.lang.Override
    public java.lang.String getPerformOperation() {
      java.lang.Object ref = performOperation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        performOperation_ = s;
        return s;
      }
    }
    /**
     * <code>string performOperation = 3;</code>
     * @return The bytes for performOperation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getPerformOperationBytes() {
      java.lang.Object ref = performOperation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        performOperation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 4;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 4;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGOPTION_FIELD_NUMBER = 5;
    private int msgOption_ = 0;
    /**
     * <code>.MessageOption msgOption = 5;</code>
     * @return The enum numeric value on the wire for msgOption.
     */
    @java.lang.Override public int getMsgOptionValue() {
      return msgOption_;
    }
    /**
     * <code>.MessageOption msgOption = 5;</code>
     * @return The msgOption.
     */
    @java.lang.Override public org.sunbird.akka.core.MessageProtos.MessageOption getMsgOption() {
      org.sunbird.akka.core.MessageProtos.MessageOption result = org.sunbird.akka.core.MessageProtos.MessageOption.forNumber(msgOption_);
      return result == null ? org.sunbird.akka.core.MessageProtos.MessageOption.UNRECOGNIZED : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 6;
    private com.google.protobuf.Value payload_;
    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     * @return Whether the payload field is set.
     */
    @java.lang.Override
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.Value getPayload() {
      return payload_ == null ? com.google.protobuf.Value.getDefaultInstance() : payload_;
    }
    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ValueOrBuilder getPayloadOrBuilder() {
      return payload_ == null ? com.google.protobuf.Value.getDefaultInstance() : payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetActorName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, targetActorName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceActorName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, sourceActorName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(performOperation_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, performOperation_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, id_);
      }
      if (msgOption_ != org.sunbird.akka.core.MessageProtos.MessageOption.SEND_AND_FORGET.getNumber()) {
        output.writeEnum(5, msgOption_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(6, getPayload());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetActorName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, targetActorName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceActorName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sourceActorName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(performOperation_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, performOperation_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, id_);
      }
      if (msgOption_ != org.sunbird.akka.core.MessageProtos.MessageOption.SEND_AND_FORGET.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
                .computeEnumSize(5, msgOption_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(6, getPayload());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof org.sunbird.akka.core.MessageProtos.Message)) {
        return super.equals(obj);
      }
      org.sunbird.akka.core.MessageProtos.Message other = (org.sunbird.akka.core.MessageProtos.Message) obj;

      if (!getTargetActorName()
              .equals(other.getTargetActorName())) return false;
      if (!getSourceActorName()
              .equals(other.getSourceActorName())) return false;
      if (!getPerformOperation()
              .equals(other.getPerformOperation())) return false;
      if (!getId()
              .equals(other.getId())) return false;
      if (msgOption_ != other.msgOption_) return false;
      if (hasPayload() != other.hasPayload()) return false;
      if (hasPayload()) {
        if (!getPayload()
                .equals(other.getPayload())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TARGETACTORNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTargetActorName().hashCode();
      hash = (37 * hash) + SOURCEACTORNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSourceActorName().hashCode();
      hash = (37 * hash) + PERFORMOPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getPerformOperation().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + MSGOPTION_FIELD_NUMBER;
      hash = (53 * hash) + msgOption_;
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
              .parseWithIOException(PARSER, input);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.sunbird.akka.core.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.sunbird.akka.core.MessageProtos.Message parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
              .parseWithIOException(PARSER, input);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sunbird.akka.core.MessageProtos.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Message)
            org.sunbird.akka.core.MessageProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.sunbird.akka.core.MessageProtos.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.sunbird.akka.core.MessageProtos.internal_static_Message_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.sunbird.akka.core.MessageProtos.Message.class, org.sunbird.akka.core.MessageProtos.Message.Builder.class);
      }

      // Construct using org.sunbird.akka.core.MessageProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getPayloadFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        targetActorName_ = "";
        sourceActorName_ = "";
        performOperation_ = "";
        id_ = "";
        msgOption_ = 0;
        payload_ = null;
        if (payloadBuilder_ != null) {
          payloadBuilder_.dispose();
          payloadBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return org.sunbird.akka.core.MessageProtos.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public org.sunbird.akka.core.MessageProtos.Message getDefaultInstanceForType() {
        return org.sunbird.akka.core.MessageProtos.Message.getDefaultInstance();
      }

      @java.lang.Override
      public org.sunbird.akka.core.MessageProtos.Message build() {
        org.sunbird.akka.core.MessageProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sunbird.akka.core.MessageProtos.Message buildPartial() {
        org.sunbird.akka.core.MessageProtos.Message result = new org.sunbird.akka.core.MessageProtos.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.sunbird.akka.core.MessageProtos.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.targetActorName_ = targetActorName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sourceActorName_ = sourceActorName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.performOperation_ = performOperation_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.msgOption_ = msgOption_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.payload_ = payloadBuilder_ == null
                  ? payload_
                  : payloadBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sunbird.akka.core.MessageProtos.Message) {
          return mergeFrom((org.sunbird.akka.core.MessageProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sunbird.akka.core.MessageProtos.Message other) {
        if (other == org.sunbird.akka.core.MessageProtos.Message.getDefaultInstance()) return this;
        if (!other.getTargetActorName().isEmpty()) {
          targetActorName_ = other.targetActorName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getSourceActorName().isEmpty()) {
          sourceActorName_ = other.sourceActorName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPerformOperation().isEmpty()) {
          performOperation_ = other.performOperation_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.msgOption_ != 0) {
          setMsgOptionValue(other.getMsgOptionValue());
        }
        if (other.hasPayload()) {
          mergePayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                targetActorName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                sourceActorName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                performOperation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                msgOption_ = input.readEnum();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                input.readMessage(
                        getPayloadFieldBuilder().getBuilder(),
                        extensionRegistry);
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object targetActorName_ = "";
      /**
       * <code>string targetActorName = 1;</code>
       * @return The targetActorName.
       */
      public java.lang.String getTargetActorName() {
        java.lang.Object ref = targetActorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          targetActorName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string targetActorName = 1;</code>
       * @return The bytes for targetActorName.
       */
      public com.google.protobuf.ByteString
      getTargetActorNameBytes() {
        java.lang.Object ref = targetActorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          targetActorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string targetActorName = 1;</code>
       * @param value The targetActorName to set.
       * @return This builder for chaining.
       */
      public Builder setTargetActorName(
              java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        targetActorName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string targetActorName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetActorName() {
        targetActorName_ = getDefaultInstance().getTargetActorName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string targetActorName = 1;</code>
       * @param value The bytes for targetActorName to set.
       * @return This builder for chaining.
       */
      public Builder setTargetActorNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        targetActorName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object sourceActorName_ = "";
      /**
       * <code>string sourceActorName = 2;</code>
       * @return The sourceActorName.
       */
      public java.lang.String getSourceActorName() {
        java.lang.Object ref = sourceActorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sourceActorName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sourceActorName = 2;</code>
       * @return The bytes for sourceActorName.
       */
      public com.google.protobuf.ByteString
      getSourceActorNameBytes() {
        java.lang.Object ref = sourceActorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          sourceActorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sourceActorName = 2;</code>
       * @param value The sourceActorName to set.
       * @return This builder for chaining.
       */
      public Builder setSourceActorName(
              java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sourceActorName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string sourceActorName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceActorName() {
        sourceActorName_ = getDefaultInstance().getSourceActorName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string sourceActorName = 2;</code>
       * @param value The bytes for sourceActorName to set.
       * @return This builder for chaining.
       */
      public Builder setSourceActorNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sourceActorName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object performOperation_ = "";
      /**
       * <code>string performOperation = 3;</code>
       * @return The performOperation.
       */
      public java.lang.String getPerformOperation() {
        java.lang.Object ref = performOperation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          performOperation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string performOperation = 3;</code>
       * @return The bytes for performOperation.
       */
      public com.google.protobuf.ByteString
      getPerformOperationBytes() {
        java.lang.Object ref = performOperation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          performOperation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string performOperation = 3;</code>
       * @param value The performOperation to set.
       * @return This builder for chaining.
       */
      public Builder setPerformOperation(
              java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        performOperation_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string performOperation = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPerformOperation() {
        performOperation_ = getDefaultInstance().getPerformOperation();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string performOperation = 3;</code>
       * @param value The bytes for performOperation to set.
       * @return This builder for chaining.
       */
      public Builder setPerformOperationBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        performOperation_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 4;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 4;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
      getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 4;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
              java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 4;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int msgOption_ = 0;
      /**
       * <code>.MessageOption msgOption = 5;</code>
       * @return The enum numeric value on the wire for msgOption.
       */
      @java.lang.Override public int getMsgOptionValue() {
        return msgOption_;
      }
      /**
       * <code>.MessageOption msgOption = 5;</code>
       * @param value The enum numeric value on the wire for msgOption to set.
       * @return This builder for chaining.
       */
      public Builder setMsgOptionValue(int value) {
        msgOption_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.MessageOption msgOption = 5;</code>
       * @return The msgOption.
       */
      @java.lang.Override
      public org.sunbird.akka.core.MessageProtos.MessageOption getMsgOption() {
        org.sunbird.akka.core.MessageProtos.MessageOption result = org.sunbird.akka.core.MessageProtos.MessageOption.forNumber(msgOption_);
        return result == null ? org.sunbird.akka.core.MessageProtos.MessageOption.UNRECOGNIZED : result;
      }
      /**
       * <code>.MessageOption msgOption = 5;</code>
       * @param value The msgOption to set.
       * @return This builder for chaining.
       */
      public Builder setMsgOption(org.sunbird.akka.core.MessageProtos.MessageOption value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        msgOption_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MessageOption msgOption = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgOption() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgOption_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Value payload_;
      private com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> payloadBuilder_;
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       * @return Whether the payload field is set.
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       * @return The payload.
       */
      public com.google.protobuf.Value getPayload() {
        if (payloadBuilder_ == null) {
          return payload_ == null ? com.google.protobuf.Value.getDefaultInstance() : payload_;
        } else {
          return payloadBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public Builder setPayload(com.google.protobuf.Value value) {
        if (payloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
        } else {
          payloadBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public Builder setPayload(
              com.google.protobuf.Value.Builder builderForValue) {
        if (payloadBuilder_ == null) {
          payload_ = builderForValue.build();
        } else {
          payloadBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public Builder mergePayload(com.google.protobuf.Value value) {
        if (payloadBuilder_ == null) {
          if (((bitField0_ & 0x00000020) != 0) &&
                  payload_ != null &&
                  payload_ != com.google.protobuf.Value.getDefaultInstance()) {
            getPayloadBuilder().mergeFrom(value);
          } else {
            payload_ = value;
          }
        } else {
          payloadBuilder_.mergeFrom(value);
        }
        if (payload_ != null) {
          bitField0_ |= 0x00000020;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000020);
        payload_ = null;
        if (payloadBuilder_ != null) {
          payloadBuilder_.dispose();
          payloadBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public com.google.protobuf.Value.Builder getPayloadBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getPayloadFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public com.google.protobuf.ValueOrBuilder getPayloadOrBuilder() {
        if (payloadBuilder_ != null) {
          return payloadBuilder_.getMessageOrBuilder();
        } else {
          return payload_ == null ?
                  com.google.protobuf.Value.getDefaultInstance() : payload_;
        }
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder>
      getPayloadFieldBuilder() {
        if (payloadBuilder_ == null) {
          payloadBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                  com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder>(
                  getPayload(),
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        return payloadBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final org.sunbird.akka.core.MessageProtos.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sunbird.akka.core.MessageProtos.Message();
    }

    public static org.sunbird.akka.core.MessageProtos.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
            PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sunbird.akka.core.MessageProtos.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_Message_descriptor;
  private static final
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\rMessage.proto\032\034google/protobuf/struct." +
                    "proto\"\255\001\n\007Message\022\027\n\017targetActorName\030\001 \001" +
                    "(\t\022\027\n\017sourceActorName\030\002 \001(\t\022\030\n\020performOp" +
                    "eration\030\003 \001(\t\022\n\n\002id\030\004 \001(\t\022!\n\tmsgOption\030\005" +
                    " \001(\0162\016.MessageOption\022\'\n\007payload\030\006 \001(\0132\026." +
                    "google.protobuf.Value*;\n\rMessageOption\022\023" +
                    "\n\017SEND_AND_FORGET\020\000\022\025\n\021GET_BACK_RESPONSE" +
                    "\020\001B&\n\025org.sunbird.akka.coreB\rMessageProt" +
                    "osb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                            com.google.protobuf.StructProto.getDescriptor(),
                    });
    internal_static_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_Message_descriptor,
            new java.lang.String[] { "TargetActorName", "SourceActorName", "PerformOperation", "Id", "MsgOption", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
