// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package org.sunbird.akka.core;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageOption}
   */
  public enum MessageOption
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SEND_AND_FORGET = 0;</code>
     */
    SEND_AND_FORGET(0),
    /**
     * <code>GET_BACK_RESPONSE = 1;</code>
     */
    GET_BACK_RESPONSE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SEND_AND_FORGET = 0;</code>
     */
    public static final int SEND_AND_FORGET_VALUE = 0;
    /**
     * <code>GET_BACK_RESPONSE = 1;</code>
     */
    public static final int GET_BACK_RESPONSE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageOption valueOf(int value) {
      return forNumber(value);
    }

    public static MessageOption forNumber(int value) {
      switch (value) {
        case 0: return SEND_AND_FORGET;
        case 1: return GET_BACK_RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageOption>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageOption> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageOption>() {
            public MessageOption findValueByNumber(int number) {
              return MessageOption.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.sunbird.akka.core.MessageProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageOption[] VALUES = values();

    public static MessageOption valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageOption(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageOption)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string targetActorName = 1;</code>
     */
    java.lang.String getTargetActorName();
    /**
     * <code>string targetActorName = 1;</code>
     */
    com.google.protobuf.ByteString
        getTargetActorNameBytes();

    /**
     * <code>string sourceActorName = 2;</code>
     */
    java.lang.String getSourceActorName();
    /**
     * <code>string sourceActorName = 2;</code>
     */
    com.google.protobuf.ByteString
        getSourceActorNameBytes();

    /**
     * <code>string performOperation = 3;</code>
     */
    java.lang.String getPerformOperation();
    /**
     * <code>string performOperation = 3;</code>
     */
    com.google.protobuf.ByteString
        getPerformOperationBytes();

    /**
     * <code>string id = 4;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 4;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.MessageOption msgOption = 5;</code>
     */
    int getMsgOptionValue();
    /**
     * <code>.MessageOption msgOption = 5;</code>
     */
    org.sunbird.akka.core.MessageProtos.MessageOption getMsgOption();

    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     */
    boolean hasPayload();
    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     */
    com.google.protobuf.Value getPayload();
    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     */
    com.google.protobuf.ValueOrBuilder getPayloadOrBuilder();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      targetActorName_ = "";
      sourceActorName_ = "";
      performOperation_ = "";
      id_ = "";
      msgOption_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              targetActorName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sourceActorName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              performOperation_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              msgOption_ = rawValue;
              break;
            }
            case 50: {
              com.google.protobuf.Value.Builder subBuilder = null;
              if (payload_ != null) {
                subBuilder = payload_.toBuilder();
              }
              payload_ = input.readMessage(com.google.protobuf.Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(payload_);
                payload_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sunbird.akka.core.MessageProtos.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sunbird.akka.core.MessageProtos.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sunbird.akka.core.MessageProtos.Message.class, org.sunbird.akka.core.MessageProtos.Message.Builder.class);
    }

    public static final int TARGETACTORNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object targetActorName_;
    /**
     * <code>string targetActorName = 1;</code>
     */
    public java.lang.String getTargetActorName() {
      java.lang.Object ref = targetActorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetActorName_ = s;
        return s;
      }
    }
    /**
     * <code>string targetActorName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTargetActorNameBytes() {
      java.lang.Object ref = targetActorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetActorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCEACTORNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object sourceActorName_;
    /**
     * <code>string sourceActorName = 2;</code>
     */
    public java.lang.String getSourceActorName() {
      java.lang.Object ref = sourceActorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceActorName_ = s;
        return s;
      }
    }
    /**
     * <code>string sourceActorName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSourceActorNameBytes() {
      java.lang.Object ref = sourceActorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceActorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERFORMOPERATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object performOperation_;
    /**
     * <code>string performOperation = 3;</code>
     */
    public java.lang.String getPerformOperation() {
      java.lang.Object ref = performOperation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        performOperation_ = s;
        return s;
      }
    }
    /**
     * <code>string performOperation = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPerformOperationBytes() {
      java.lang.Object ref = performOperation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        performOperation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 4;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGOPTION_FIELD_NUMBER = 5;
    private int msgOption_;
    /**
     * <code>.MessageOption msgOption = 5;</code>
     */
    public int getMsgOptionValue() {
      return msgOption_;
    }
    /**
     * <code>.MessageOption msgOption = 5;</code>
     */
    public org.sunbird.akka.core.MessageProtos.MessageOption getMsgOption() {
      @SuppressWarnings("deprecation")
      org.sunbird.akka.core.MessageProtos.MessageOption result = org.sunbird.akka.core.MessageProtos.MessageOption.valueOf(msgOption_);
      return result == null ? org.sunbird.akka.core.MessageProtos.MessageOption.UNRECOGNIZED : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 6;
    private com.google.protobuf.Value payload_;
    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     */
    public boolean hasPayload() {
      return payload_ != null;
    }
    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     */
    public com.google.protobuf.Value getPayload() {
      return payload_ == null ? com.google.protobuf.Value.getDefaultInstance() : payload_;
    }
    /**
     * <code>.google.protobuf.Value payload = 6;</code>
     */
    public com.google.protobuf.ValueOrBuilder getPayloadOrBuilder() {
      return getPayload();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTargetActorNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, targetActorName_);
      }
      if (!getSourceActorNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sourceActorName_);
      }
      if (!getPerformOperationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, performOperation_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, id_);
      }
      if (msgOption_ != org.sunbird.akka.core.MessageProtos.MessageOption.SEND_AND_FORGET.getNumber()) {
        output.writeEnum(5, msgOption_);
      }
      if (payload_ != null) {
        output.writeMessage(6, getPayload());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTargetActorNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, targetActorName_);
      }
      if (!getSourceActorNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sourceActorName_);
      }
      if (!getPerformOperationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, performOperation_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, id_);
      }
      if (msgOption_ != org.sunbird.akka.core.MessageProtos.MessageOption.SEND_AND_FORGET.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, msgOption_);
      }
      if (payload_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getPayload());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sunbird.akka.core.MessageProtos.Message)) {
        return super.equals(obj);
      }
      org.sunbird.akka.core.MessageProtos.Message other = (org.sunbird.akka.core.MessageProtos.Message) obj;

      boolean result = true;
      result = result && getTargetActorName()
          .equals(other.getTargetActorName());
      result = result && getSourceActorName()
          .equals(other.getSourceActorName());
      result = result && getPerformOperation()
          .equals(other.getPerformOperation());
      result = result && getId()
          .equals(other.getId());
      result = result && msgOption_ == other.msgOption_;
      result = result && (hasPayload() == other.hasPayload());
      if (hasPayload()) {
        result = result && getPayload()
            .equals(other.getPayload());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TARGETACTORNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTargetActorName().hashCode();
      hash = (37 * hash) + SOURCEACTORNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSourceActorName().hashCode();
      hash = (37 * hash) + PERFORMOPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getPerformOperation().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + MSGOPTION_FIELD_NUMBER;
      hash = (53 * hash) + msgOption_;
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sunbird.akka.core.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sunbird.akka.core.MessageProtos.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        org.sunbird.akka.core.MessageProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sunbird.akka.core.MessageProtos.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sunbird.akka.core.MessageProtos.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sunbird.akka.core.MessageProtos.Message.class, org.sunbird.akka.core.MessageProtos.Message.Builder.class);
      }

      // Construct using org.sunbird.akka.core.MessageProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        targetActorName_ = "";

        sourceActorName_ = "";

        performOperation_ = "";

        id_ = "";

        msgOption_ = 0;

        if (payloadBuilder_ == null) {
          payload_ = null;
        } else {
          payload_ = null;
          payloadBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sunbird.akka.core.MessageProtos.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public org.sunbird.akka.core.MessageProtos.Message getDefaultInstanceForType() {
        return org.sunbird.akka.core.MessageProtos.Message.getDefaultInstance();
      }

      @java.lang.Override
      public org.sunbird.akka.core.MessageProtos.Message build() {
        org.sunbird.akka.core.MessageProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sunbird.akka.core.MessageProtos.Message buildPartial() {
        org.sunbird.akka.core.MessageProtos.Message result = new org.sunbird.akka.core.MessageProtos.Message(this);
        result.targetActorName_ = targetActorName_;
        result.sourceActorName_ = sourceActorName_;
        result.performOperation_ = performOperation_;
        result.id_ = id_;
        result.msgOption_ = msgOption_;
        if (payloadBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = payloadBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sunbird.akka.core.MessageProtos.Message) {
          return mergeFrom((org.sunbird.akka.core.MessageProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sunbird.akka.core.MessageProtos.Message other) {
        if (other == org.sunbird.akka.core.MessageProtos.Message.getDefaultInstance()) return this;
        if (!other.getTargetActorName().isEmpty()) {
          targetActorName_ = other.targetActorName_;
          onChanged();
        }
        if (!other.getSourceActorName().isEmpty()) {
          sourceActorName_ = other.sourceActorName_;
          onChanged();
        }
        if (!other.getPerformOperation().isEmpty()) {
          performOperation_ = other.performOperation_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.msgOption_ != 0) {
          setMsgOptionValue(other.getMsgOptionValue());
        }
        if (other.hasPayload()) {
          mergePayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sunbird.akka.core.MessageProtos.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sunbird.akka.core.MessageProtos.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object targetActorName_ = "";
      /**
       * <code>string targetActorName = 1;</code>
       */
      public java.lang.String getTargetActorName() {
        java.lang.Object ref = targetActorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          targetActorName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string targetActorName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTargetActorNameBytes() {
        java.lang.Object ref = targetActorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetActorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string targetActorName = 1;</code>
       */
      public Builder setTargetActorName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        targetActorName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string targetActorName = 1;</code>
       */
      public Builder clearTargetActorName() {
        
        targetActorName_ = getDefaultInstance().getTargetActorName();
        onChanged();
        return this;
      }
      /**
       * <code>string targetActorName = 1;</code>
       */
      public Builder setTargetActorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        targetActorName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sourceActorName_ = "";
      /**
       * <code>string sourceActorName = 2;</code>
       */
      public java.lang.String getSourceActorName() {
        java.lang.Object ref = sourceActorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sourceActorName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sourceActorName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSourceActorNameBytes() {
        java.lang.Object ref = sourceActorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceActorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sourceActorName = 2;</code>
       */
      public Builder setSourceActorName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sourceActorName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sourceActorName = 2;</code>
       */
      public Builder clearSourceActorName() {
        
        sourceActorName_ = getDefaultInstance().getSourceActorName();
        onChanged();
        return this;
      }
      /**
       * <code>string sourceActorName = 2;</code>
       */
      public Builder setSourceActorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sourceActorName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object performOperation_ = "";
      /**
       * <code>string performOperation = 3;</code>
       */
      public java.lang.String getPerformOperation() {
        java.lang.Object ref = performOperation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          performOperation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string performOperation = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPerformOperationBytes() {
        java.lang.Object ref = performOperation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          performOperation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string performOperation = 3;</code>
       */
      public Builder setPerformOperation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        performOperation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string performOperation = 3;</code>
       */
      public Builder clearPerformOperation() {
        
        performOperation_ = getDefaultInstance().getPerformOperation();
        onChanged();
        return this;
      }
      /**
       * <code>string performOperation = 3;</code>
       */
      public Builder setPerformOperationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        performOperation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 4;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 4;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 4;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 4;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int msgOption_ = 0;
      /**
       * <code>.MessageOption msgOption = 5;</code>
       */
      public int getMsgOptionValue() {
        return msgOption_;
      }
      /**
       * <code>.MessageOption msgOption = 5;</code>
       */
      public Builder setMsgOptionValue(int value) {
        msgOption_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MessageOption msgOption = 5;</code>
       */
      public org.sunbird.akka.core.MessageProtos.MessageOption getMsgOption() {
        @SuppressWarnings("deprecation")
        org.sunbird.akka.core.MessageProtos.MessageOption result = org.sunbird.akka.core.MessageProtos.MessageOption.valueOf(msgOption_);
        return result == null ? org.sunbird.akka.core.MessageProtos.MessageOption.UNRECOGNIZED : result;
      }
      /**
       * <code>.MessageOption msgOption = 5;</code>
       */
      public Builder setMsgOption(org.sunbird.akka.core.MessageProtos.MessageOption value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgOption_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MessageOption msgOption = 5;</code>
       */
      public Builder clearMsgOption() {
        
        msgOption_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Value payload_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> payloadBuilder_;
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public boolean hasPayload() {
        return payloadBuilder_ != null || payload_ != null;
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public com.google.protobuf.Value getPayload() {
        if (payloadBuilder_ == null) {
          return payload_ == null ? com.google.protobuf.Value.getDefaultInstance() : payload_;
        } else {
          return payloadBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public Builder setPayload(com.google.protobuf.Value value) {
        if (payloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          payloadBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public Builder setPayload(
          com.google.protobuf.Value.Builder builderForValue) {
        if (payloadBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          payloadBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public Builder mergePayload(com.google.protobuf.Value value) {
        if (payloadBuilder_ == null) {
          if (payload_ != null) {
            payload_ =
              com.google.protobuf.Value.newBuilder(payload_).mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          payloadBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public Builder clearPayload() {
        if (payloadBuilder_ == null) {
          payload_ = null;
          onChanged();
        } else {
          payload_ = null;
          payloadBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public com.google.protobuf.Value.Builder getPayloadBuilder() {
        
        onChanged();
        return getPayloadFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      public com.google.protobuf.ValueOrBuilder getPayloadOrBuilder() {
        if (payloadBuilder_ != null) {
          return payloadBuilder_.getMessageOrBuilder();
        } else {
          return payload_ == null ?
              com.google.protobuf.Value.getDefaultInstance() : payload_;
        }
      }
      /**
       * <code>.google.protobuf.Value payload = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> 
          getPayloadFieldBuilder() {
        if (payloadBuilder_ == null) {
          payloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder>(
                  getPayload(),
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        return payloadBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final org.sunbird.akka.core.MessageProtos.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sunbird.akka.core.MessageProtos.Message();
    }

    public static org.sunbird.akka.core.MessageProtos.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sunbird.akka.core.MessageProtos.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\032\034google/protobuf/struct." +
      "proto\"\255\001\n\007Message\022\027\n\017targetActorName\030\001 \001" +
      "(\t\022\027\n\017sourceActorName\030\002 \001(\t\022\030\n\020performOp" +
      "eration\030\003 \001(\t\022\n\n\002id\030\004 \001(\t\022!\n\tmsgOption\030\005" +
      " \001(\0162\016.MessageOption\022\'\n\007payload\030\006 \001(\0132\026." +
      "google.protobuf.Value*;\n\rMessageOption\022\023" +
      "\n\017SEND_AND_FORGET\020\000\022\025\n\021GET_BACK_RESPONSE" +
      "\020\001B&\n\025org.sunbird.akka.coreB\rMessageProt" +
      "osb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        }, assigner);
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "TargetActorName", "SourceActorName", "PerformOperation", "Id", "MsgOption", "Payload", });
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
