// Code generated by go-swagger; DO NOT EDIT.

package pull_certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"digilocker_certificate_api/swagger_gen/models"
)

// NewPostV1DigilockerPullURIRequestParams creates a new PostV1DigilockerPullURIRequestParams object
//
// There are no default values defined in the spec.
func NewPostV1DigilockerPullURIRequestParams() PostV1DigilockerPullURIRequestParams {

	return PostV1DigilockerPullURIRequestParams{}
}

// PostV1DigilockerPullURIRequestParams contains all the bound params for the post v1 digilocker pull URI request operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostV1DigilockerPullURIRequest
type PostV1DigilockerPullURIRequestParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*PullUriRequest
	  In: body
	*/
	Body *models.PullURIRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostV1DigilockerPullURIRequestParams() beforehand.
func (o *PostV1DigilockerPullURIRequestParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.PullURIRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
