// Code generated by go-swagger; DO NOT EDIT.

package pull_certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"digilocker_certificate_api/swagger_gen/models"
)

// PostV1DigilockerPullURIRequestOKCode is the HTTP code returned for type PostV1DigilockerPullURIRequestOK
const PostV1DigilockerPullURIRequestOKCode int = 200

/*
PostV1DigilockerPullURIRequestOK OK

swagger:response postV1DigilockerPullUriRequestOK
*/
type PostV1DigilockerPullURIRequestOK struct {

	/*
	  In: Body
	*/
	Payload *models.PullURIRequestOKResponse `json:"body,omitempty"`
}

// NewPostV1DigilockerPullURIRequestOK creates PostV1DigilockerPullURIRequestOK with default headers values
func NewPostV1DigilockerPullURIRequestOK() *PostV1DigilockerPullURIRequestOK {

	return &PostV1DigilockerPullURIRequestOK{}
}

// WithPayload adds the payload to the post v1 digilocker pull Uri request o k response
func (o *PostV1DigilockerPullURIRequestOK) WithPayload(payload *models.PullURIRequestOKResponse) *PostV1DigilockerPullURIRequestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 digilocker pull Uri request o k response
func (o *PostV1DigilockerPullURIRequestOK) SetPayload(payload *models.PullURIRequestOKResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1DigilockerPullURIRequestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
