// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Digilocker Certificate API
//
//	Pull Credentials to Digilocker
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/xml
//
//	Produces:
//	  - application/xml
//
// swagger:meta
package restapi
