// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/xml"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Pull Credentials to Digilocker",
    "title": "Digilocker Certificate API",
    "version": "1.0.0"
  },
  "paths": {
    "/heath": {
      "get": {
        "description": "API to get the notification health status",
        "tags": [
          "health"
        ],
        "summary": "Get the health status",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/HealthOKResponse"
            }
          }
        }
      }
    },
    "/v1/digilocker/pullUriRequest": {
      "post": {
        "description": "API to pull the credentials in digilocker",
        "consumes": [
          "application/xml"
        ],
        "produces": [
          "application/xml"
        ],
        "tags": [
          "pull certificates"
        ],
        "summary": "Pull certificates in digilocker",
        "parameters": [
          {
            "description": "PullUriRequest",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/PullURIRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/PullURIRequestOKResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "HealthOKResponse": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        }
      }
    },
    "PullURIRequest": {
      "type": "object",
      "properties": {
        "DocDetails": {
          "type": "object",
          "properties": {
            "CertificateId": {
              "type": "string"
            },
            "DOB": {
              "type": "string"
            },
            "DigiLockerId": {
              "type": "string"
            },
            "DocType": {
              "type": "string"
            },
            "FullName": {
              "type": "string"
            },
            "Mobile": {
              "type": "string"
            },
            "Photo": {
              "type": "string"
            },
            "Text": {
              "type": "string"
            },
            "TrackingId": {
              "type": "string"
            },
            "UDF1": {
              "type": "string"
            },
            "UDF2": {
              "type": "string"
            },
            "UDF3": {
              "type": "string"
            },
            "UDFn": {
              "type": "string"
            },
            "UID": {
              "type": "string"
            }
          }
        },
        "Format": {
          "type": "string"
        },
        "Ns2": {
          "type": "string"
        },
        "OrgId": {
          "type": "string"
        },
        "Text": {
          "type": "string"
        },
        "Ts": {
          "type": "string"
        },
        "Txn": {
          "type": "string"
        },
        "Ver": {
          "type": "string"
        },
        "XMLName": {
          "type": "string"
        }
      }
    },
    "PullURIRequestOKResponse": {
      "type": "object",
      "properties": {
        "DocDetails": {
          "type": "object",
          "properties": {
            "CertificateId": {
              "type": "string"
            },
            "DOB": {
              "type": "string"
            },
            "DataContent": {
              "type": "string"
            },
            "DigiLockerId": {
              "type": "string"
            },
            "DocContent": {
              "type": "string"
            },
            "DocType": {
              "type": "string"
            },
            "FullName": {
              "type": "string"
            },
            "Mobile": {
              "type": "string"
            },
            "Text": {
              "type": "string"
            },
            "UDF1": {
              "type": "string"
            },
            "UID": {
              "type": "string"
            },
            "URI": {
              "type": "string"
            }
          }
        },
        "Ns2": {
          "type": "string"
        },
        "ResponseStatus": {
          "type": "object",
          "properties": {
            "Status": {
              "type": "string"
            },
            "Text": {
              "type": "string"
            },
            "Ts": {
              "type": "string"
            },
            "Txn": {
              "type": "string"
            }
          }
        },
        "Text": {
          "type": "string"
        },
        "XMLName": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/xml"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Pull Credentials to Digilocker",
    "title": "Digilocker Certificate API",
    "version": "1.0.0"
  },
  "paths": {
    "/heath": {
      "get": {
        "description": "API to get the notification health status",
        "tags": [
          "health"
        ],
        "summary": "Get the health status",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/HealthOKResponse"
            }
          }
        }
      }
    },
    "/v1/digilocker/pullUriRequest": {
      "post": {
        "description": "API to pull the credentials in digilocker",
        "consumes": [
          "application/xml"
        ],
        "produces": [
          "application/xml"
        ],
        "tags": [
          "pull certificates"
        ],
        "summary": "Pull certificates in digilocker",
        "parameters": [
          {
            "description": "PullUriRequest",
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/PullURIRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/PullURIRequestOKResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "HealthOKResponse": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        }
      }
    },
    "PullURIRequest": {
      "type": "object",
      "properties": {
        "DocDetails": {
          "type": "object",
          "properties": {
            "CertificateId": {
              "type": "string"
            },
            "DOB": {
              "type": "string"
            },
            "DigiLockerId": {
              "type": "string"
            },
            "DocType": {
              "type": "string"
            },
            "FullName": {
              "type": "string"
            },
            "Mobile": {
              "type": "string"
            },
            "Photo": {
              "type": "string"
            },
            "Text": {
              "type": "string"
            },
            "TrackingId": {
              "type": "string"
            },
            "UDF1": {
              "type": "string"
            },
            "UDF2": {
              "type": "string"
            },
            "UDF3": {
              "type": "string"
            },
            "UDFn": {
              "type": "string"
            },
            "UID": {
              "type": "string"
            }
          }
        },
        "Format": {
          "type": "string"
        },
        "Ns2": {
          "type": "string"
        },
        "OrgId": {
          "type": "string"
        },
        "Text": {
          "type": "string"
        },
        "Ts": {
          "type": "string"
        },
        "Txn": {
          "type": "string"
        },
        "Ver": {
          "type": "string"
        },
        "XMLName": {
          "type": "string"
        }
      }
    },
    "PullURIRequestDocDetails": {
      "type": "object",
      "properties": {
        "CertificateId": {
          "type": "string"
        },
        "DOB": {
          "type": "string"
        },
        "DigiLockerId": {
          "type": "string"
        },
        "DocType": {
          "type": "string"
        },
        "FullName": {
          "type": "string"
        },
        "Mobile": {
          "type": "string"
        },
        "Photo": {
          "type": "string"
        },
        "Text": {
          "type": "string"
        },
        "TrackingId": {
          "type": "string"
        },
        "UDF1": {
          "type": "string"
        },
        "UDF2": {
          "type": "string"
        },
        "UDF3": {
          "type": "string"
        },
        "UDFn": {
          "type": "string"
        },
        "UID": {
          "type": "string"
        }
      }
    },
    "PullURIRequestOKResponse": {
      "type": "object",
      "properties": {
        "DocDetails": {
          "type": "object",
          "properties": {
            "CertificateId": {
              "type": "string"
            },
            "DOB": {
              "type": "string"
            },
            "DataContent": {
              "type": "string"
            },
            "DigiLockerId": {
              "type": "string"
            },
            "DocContent": {
              "type": "string"
            },
            "DocType": {
              "type": "string"
            },
            "FullName": {
              "type": "string"
            },
            "Mobile": {
              "type": "string"
            },
            "Text": {
              "type": "string"
            },
            "UDF1": {
              "type": "string"
            },
            "UID": {
              "type": "string"
            },
            "URI": {
              "type": "string"
            }
          }
        },
        "Ns2": {
          "type": "string"
        },
        "ResponseStatus": {
          "type": "object",
          "properties": {
            "Status": {
              "type": "string"
            },
            "Text": {
              "type": "string"
            },
            "Ts": {
              "type": "string"
            },
            "Txn": {
              "type": "string"
            }
          }
        },
        "Text": {
          "type": "string"
        },
        "XMLName": {
          "type": "string"
        }
      }
    },
    "PullURIRequestOKResponseDocDetails": {
      "type": "object",
      "properties": {
        "CertificateId": {
          "type": "string"
        },
        "DOB": {
          "type": "string"
        },
        "DataContent": {
          "type": "string"
        },
        "DigiLockerId": {
          "type": "string"
        },
        "DocContent": {
          "type": "string"
        },
        "DocType": {
          "type": "string"
        },
        "FullName": {
          "type": "string"
        },
        "Mobile": {
          "type": "string"
        },
        "Text": {
          "type": "string"
        },
        "UDF1": {
          "type": "string"
        },
        "UID": {
          "type": "string"
        },
        "URI": {
          "type": "string"
        }
      }
    },
    "PullURIRequestOKResponseResponseStatus": {
      "type": "object",
      "properties": {
        "Status": {
          "type": "string"
        },
        "Text": {
          "type": "string"
        },
        "Ts": {
          "type": "string"
        },
        "Txn": {
          "type": "string"
        }
      }
    }
  }
}`))
}
