// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"digilocker_certificate_api/swagger_gen/models"
)

// GetHeathOKCode is the HTTP code returned for type GetHeathOK
const GetHeathOKCode int = 200

/*
GetHeathOK OK

swagger:response getHeathOK
*/
type GetHeathOK struct {

	/*
	  In: Body
	*/
	Payload *models.HealthOKResponse `json:"body,omitempty"`
}

// NewGetHeathOK creates GetHeathOK with default headers values
func NewGetHeathOK() *GetHeathOK {

	return &GetHeathOK{}
}

// WithPayload adds the payload to the get heath o k response
func (o *GetHeathOK) WithPayload(payload *models.HealthOKResponse) *GetHeathOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get heath o k response
func (o *GetHeathOK) SetPayload(payload *models.HealthOKResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHeathOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
