// Code generated by go-swagger; DO NOT EDIT.

package sample_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"bulk_issuance/swagger_gen/models"
)

// GetV1SampleSchemaNameHandlerFunc turns a function with the right signature into a get v1 sample schema name handler
type GetV1SampleSchemaNameHandlerFunc func(GetV1SampleSchemaNameParams, *models.JWTClaimBody) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1SampleSchemaNameHandlerFunc) Handle(params GetV1SampleSchemaNameParams, principal *models.JWTClaimBody) middleware.Responder {
	return fn(params, principal)
}

// GetV1SampleSchemaNameHandler interface for that can handle valid get v1 sample schema name params
type GetV1SampleSchemaNameHandler interface {
	Handle(GetV1SampleSchemaNameParams, *models.JWTClaimBody) middleware.Responder
}

// NewGetV1SampleSchemaName creates a new http.Handler for the get v1 sample schema name operation
func NewGetV1SampleSchemaName(ctx *middleware.Context, handler GetV1SampleSchemaNameHandler) *GetV1SampleSchemaName {
	return &GetV1SampleSchemaName{Context: ctx, Handler: handler}
}

/*GetV1SampleSchemaName swagger:route GET /v1/sample/{schemaName} sampleTemplate getV1SampleSchemaName

get sample template

*/
type GetV1SampleSchemaName struct {
	Context *middleware.Context
	Handler GetV1SampleSchemaNameHandler
}

func (o *GetV1SampleSchemaName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1SampleSchemaNameParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.JWTClaimBody
	if uprinc != nil {
		principal = uprinc.(*models.JWTClaimBody) // this is really a models.JWTClaimBody, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
