// Code generated by go-swagger; DO NOT EDIT.

package sample_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetV1SchemaNameSampleCsvParams creates a new GetV1SchemaNameSampleCsvParams object
//
// There are no default values defined in the spec.
func NewGetV1SchemaNameSampleCsvParams() GetV1SchemaNameSampleCsvParams {

	return GetV1SchemaNameSampleCsvParams{}
}

// GetV1SchemaNameSampleCsvParams contains all the bound params for the get v1 schema name sample csv operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetV1SchemaNameSampleCsv
type GetV1SchemaNameSampleCsvParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*schema name
	  Required: true
	  In: path
	*/
	SchemaName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetV1SchemaNameSampleCsvParams() beforehand.
func (o *GetV1SchemaNameSampleCsvParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rSchemaName, rhkSchemaName, _ := route.Params.GetOK("schemaName")
	if err := o.bindSchemaName(rSchemaName, rhkSchemaName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSchemaName binds and validates parameter SchemaName from path.
func (o *GetV1SchemaNameSampleCsvParams) bindSchemaName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SchemaName = raw

	return nil
}
