// Code generated by go-swagger; DO NOT EDIT.

package sample_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bulk_issuance/swagger_gen/models"
)

// GetV1BulkSampleSchemaNameOKCode is the HTTP code returned for type GetV1BulkSampleSchemaNameOK
const GetV1BulkSampleSchemaNameOKCode int = 200

/*GetV1BulkSampleSchemaNameOK OK

swagger:response getV1BulkSampleSchemaNameOK
*/
type GetV1BulkSampleSchemaNameOK struct {
	/*

	 */
	ContentDisposition string `json:"Content-Disposition"`

	/*
	  In: Body
	*/
	Payload models.SampleTemplateResponse `json:"body,omitempty"`
}

// NewGetV1BulkSampleSchemaNameOK creates GetV1BulkSampleSchemaNameOK with default headers values
func NewGetV1BulkSampleSchemaNameOK() *GetV1BulkSampleSchemaNameOK {

	return &GetV1BulkSampleSchemaNameOK{}
}

// WithContentDisposition adds the contentDisposition to the get v1 bulk sample schema name o k response
func (o *GetV1BulkSampleSchemaNameOK) WithContentDisposition(contentDisposition string) *GetV1BulkSampleSchemaNameOK {
	o.ContentDisposition = contentDisposition
	return o
}

// SetContentDisposition sets the contentDisposition to the get v1 bulk sample schema name o k response
func (o *GetV1BulkSampleSchemaNameOK) SetContentDisposition(contentDisposition string) {
	o.ContentDisposition = contentDisposition
}

// WithPayload adds the payload to the get v1 bulk sample schema name o k response
func (o *GetV1BulkSampleSchemaNameOK) WithPayload(payload models.SampleTemplateResponse) *GetV1BulkSampleSchemaNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 bulk sample schema name o k response
func (o *GetV1BulkSampleSchemaNameOK) SetPayload(payload models.SampleTemplateResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1BulkSampleSchemaNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Content-Disposition

	contentDisposition := o.ContentDisposition
	if contentDisposition != "" {
		rw.Header().Set("Content-Disposition", contentDisposition)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1BulkSampleSchemaNameNotFoundCode is the HTTP code returned for type GetV1BulkSampleSchemaNameNotFound
const GetV1BulkSampleSchemaNameNotFoundCode int = 404

/*GetV1BulkSampleSchemaNameNotFound Not found

swagger:response getV1BulkSampleSchemaNameNotFound
*/
type GetV1BulkSampleSchemaNameNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1BulkSampleSchemaNameNotFound creates GetV1BulkSampleSchemaNameNotFound with default headers values
func NewGetV1BulkSampleSchemaNameNotFound() *GetV1BulkSampleSchemaNameNotFound {

	return &GetV1BulkSampleSchemaNameNotFound{}
}

// WithPayload adds the payload to the get v1 bulk sample schema name not found response
func (o *GetV1BulkSampleSchemaNameNotFound) WithPayload(payload string) *GetV1BulkSampleSchemaNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 bulk sample schema name not found response
func (o *GetV1BulkSampleSchemaNameNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1BulkSampleSchemaNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
