// Code generated by go-swagger; DO NOT EDIT.

package sample_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// GetV1BulkSampleSchemaNameURL generates an URL for the get v1 bulk sample schema name operation
type GetV1BulkSampleSchemaNameURL struct {
	SchemaName string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetV1BulkSampleSchemaNameURL) WithBasePath(bp string) *GetV1BulkSampleSchemaNameURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetV1BulkSampleSchemaNameURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetV1BulkSampleSchemaNameURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/v1/bulk/sample/{schemaName}"

	schemaName := o.SchemaName
	if schemaName != "" {
		_path = strings.Replace(_path, "{schemaName}", schemaName, -1)
	} else {
		return nil, errors.New("schemaName is required on GetV1BulkSampleSchemaNameURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetV1BulkSampleSchemaNameURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetV1BulkSampleSchemaNameURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetV1BulkSampleSchemaNameURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetV1BulkSampleSchemaNameURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetV1BulkSampleSchemaNameURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetV1BulkSampleSchemaNameURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
