// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Bulk Issuance
//
//	Bulk Issuance API
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//	  - multipart/form-data
//
//	Produces:
//	  - application/octet-stream
//	  - application/json
//
// swagger:meta
package restapi
