// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"metrics/swagger_gen/models"
)

// GetV1MetricsOKCode is the HTTP code returned for type GetV1MetricsOK
const GetV1MetricsOKCode int = 200

/*GetV1MetricsOK OK

swagger:response getV1MetricsOK
*/
type GetV1MetricsOK struct {

	/*
	  In: Body
	*/
	Payload *models.LoginResponse `json:"body,omitempty"`
}

// NewGetV1MetricsOK creates GetV1MetricsOK with default headers values
func NewGetV1MetricsOK() *GetV1MetricsOK {

	return &GetV1MetricsOK{}
}

// WithPayload adds the payload to the get v1 metrics o k response
func (o *GetV1MetricsOK) WithPayload(payload *models.LoginResponse) *GetV1MetricsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 metrics o k response
func (o *GetV1MetricsOK) SetPayload(payload *models.LoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1MetricsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
