import {
  isSelfContainedDid,
  resolveSelfContainedDidToJwk,
} from './self-contained-did.util';

// Vectors generated by a standards-compliant DID library for every signature
// algorithm a wallet may bind a credential with, so a regression here means
// a real wallet stops interoperating.
const VECTORS = [
  {
    algorithm: 'EdDSA',
    didKey: 'did:key:z6MknFqr4SUdJP8iXb6tHswwKCgKiBWJBjdK1QJqnZppXTtH',
    didJwk:
      'did:jwk:eyJrdHkiOiJPS1AiLCJjcnYiOiJFZDI1NTE5IiwieCI6ImNfQy1yT3Z2M190bTR2M2F6SENmZmlKeURyQmtQaF9lYTFNVl9vazJOc1kifQ',
    expected: {
      kty: 'OKP',
      crv: 'Ed25519',
      x: 'c_C-rOvv3_tm4v3azHCffiJyDrBkPh_ea1MV_ok2NsY',
      y: undefined,
    },
  },
  {
    algorithm: 'ES256',
    didKey: 'did:key:zDnaebmH8mtGKx1CsikSJD6z7nnWEjPxQzjrz4SW51UhqgHBd',
    didJwk:
      'did:jwk:eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6InFHTUxZendrZ1dJTXJBZjJ5N1duYzF6ZnM3VmpUd3NVVjRpZGFkM0F6NEEiLCJ5IjoiYi1OYUFuczJRMUcyMDk5WHJncVRrMVN3RXdRWkVhT1VIU3hsdDBRT0ZsbyJ9',
    expected: {
      kty: 'EC',
      crv: 'P-256',
      x: 'qGMLYzwkgWIMrAf2y7Wnc1zfs7VjTwsUV4idad3Az4A',
      y: 'b-NaAns2Q1G2099XrgqTk1SwEwQZEaOUHSxlt0QOFlo',
    },
  },
  {
    algorithm: 'ES384',
    didKey:
      'did:key:z82LkyobivwLhRMMr9JBtTeZDCipiFuLC231ReDZDJiBo9wQL3WMbUoqb7pG13JfPC1UHbQ',
    didJwk:
      'did:jwk:eyJrdHkiOiJFQyIsImNydiI6IlAtMzg0IiwieCI6ImFpTFRjTUZPMVdYbFgzNW5JeXpISTFIMVV6cHFjVFlnTVRGc3dfaFdDUnZ2TGZ1ZXJaOS1GS184VW5FWlNFLWoiLCJ5IjoiWUx1QTRZNkRSNzFhbXl2ckx3bndGVmtTTkdoZ1hneHBKRDdaNXNOOUVqYndQeDJQNUtDQU9zTUZiWlhmb0I1NyJ9',
    expected: {
      kty: 'EC',
      crv: 'P-384',
      x: 'aiLTcMFO1WXlX35nIyzHI1H1UzpqcTYgMTFsw_hWCRvvLfuerZ9-FK_8UnEZSE-j',
      y: 'YLuA4Y6DR71amyvrLwnwFVkSNGhgXgxpJD7Z5sN9EjbwPx2P5KCAOsMFbZXfoB57',
    },
  },
  {
    algorithm: 'ES256K',
    didKey: 'did:key:zQ3shvmK8cLUbHqp2tXW7UnF4eQiGhQAAioWKBStEbA3ZqWzd',
    didJwk:
      'did:jwk:eyJrdHkiOiJFQyIsImNydiI6InNlY3AyNTZrMSIsIngiOiI3NU9oVjl4cV8yUl9aLUUyMHlEVm1HNkpLeVBsNFE3eExvQm1PMlRTeXlJIiwieSI6IndzWmphcGV2LUVmRmVFamk1d3ZkSlV1VkNvblBWLW9ndDlFamFLeEpiMnMifQ',
    expected: {
      kty: 'EC',
      crv: 'secp256k1',
      x: '75OhV9xq_2R_Z-E20yDVmG6JKyPl4Q7xLoBmO2TSyyI',
      y: 'wsZjapev-EfFeEji5wvdJUuVConPV-ogt9EjaKxJb2s',
    },
  },
] as const;

const material = (jwk: any) => ({
  kty: jwk?.kty,
  crv: jwk?.crv,
  x: jwk?.x,
  y: jwk?.y,
});

describe('self-contained DID resolution', () => {
  describe.each(VECTORS)('$algorithm', ({ didKey, didJwk, expected }) => {
    it('resolves did:key to the right public JWK', () => {
      expect(material(resolveSelfContainedDidToJwk(didKey))).toEqual(
        material(expected),
      );
    });

    it('resolves did:jwk to the right public JWK', () => {
      expect(material(resolveSelfContainedDidToJwk(didJwk))).toEqual(
        material(expected),
      );
    });
  });

  it('accepts the DID part of a kid with a fragment', () => {
    const { didKey, expected } = VECTORS[1];
    const kid = `${didKey}#${didKey.slice('did:key:'.length)}`;
    expect(material(resolveSelfContainedDidToJwk(kid.split('#')[0]))).toEqual(
      material(expected),
    );
  });

  // Registry-backed methods must keep going to identity-service.
  it.each(['did:web:example.com', 'did:rcw:abc123', undefined])(
    'returns undefined for %s',
    (did) => {
      expect(resolveSelfContainedDidToJwk(did as string)).toBeUndefined();
    },
  );

  it('throws on a malformed did:key payload', () => {
    expect(() => resolveSelfContainedDidToJwk('did:key:zNOTBASE58!!')).toThrow(
      /malformed did:key/,
    );
  });

  it('throws on an unsupported multibase encoding', () => {
    expect(() => resolveSelfContainedDidToJwk('did:key:Qabc')).toThrow(
      /multibase/,
    );
  });

  it('throws on a malformed did:jwk payload', () => {
    expect(() => resolveSelfContainedDidToJwk('did:jwk:!!!')).toThrow(
      /malformed did:jwk/,
    );
  });

  it('classifies self-contained methods', () => {
    expect(isSelfContainedDid(VECTORS[0].didKey)).toBe(true);
    expect(isSelfContainedDid(VECTORS[0].didJwk)).toBe(true);
    expect(isSelfContainedDid('did:web:example.com')).toBe(false);
    expect(isSelfContainedDid(undefined)).toBe(false);
  });
});
