// Code generated by go-swagger; DO NOT EDIT.

package notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetNotificationOKCode is the HTTP code returned for type GetNotificationOK
const GetNotificationOKCode int = 200

/*GetNotificationOK OK

swagger:response getNotificationOK
*/
type GetNotificationOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetNotificationOK creates GetNotificationOK with default headers values
func NewGetNotificationOK() *GetNotificationOK {

	return &GetNotificationOK{}
}

// WithPayload adds the payload to the get notification o k response
func (o *GetNotificationOK) WithPayload(payload interface{}) *GetNotificationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get notification o k response
func (o *GetNotificationOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNotificationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
